services:
  db:
    image: postgres
    container_name: gomarket-db
    restart: always
    environment:
      POSTGRES_USER: gomarket
      POSTGRES_PASSWORD: gomarketpass
      POSTGRES_DB: gomarketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
